set SYN_TARG 1.33
set RC_LATENCY -1
set FILE acc
set TOP  acc
set DENSITY_FACTOR 0.5
set VERILOG_SEARCH_DIRS {}
set SCAN_VERILOG {}
set USE_GATES_FILE /home/scf-12/ee552/proteus/pdk/proteus/qdi.gates
set OPERAND_ISOLATION 0
lappend INCLUDE_VERILOG /home/scf-12/ee552/proteus/pdk/proteus/qdi.include.sv
lappend INCLUDE_VERILOG /home/scf-12/ee552/proteus/pdk/proteus/e1ofN_M.sv
lappend INCLUDE_VERILOG /home/scf-12/ee552/proteus/pdk/proteus/rtl_interface.sv
lappend INCLUDE_VERILOG /home/scf-30/huayufu/acc/acc.rtl.sv
set RC_LIB_FILE "/home/scf-12/ee552/proteus/pdk/proteus/qdi_image_ta.lib"
set PROTEUS_LIBS "/home/scf-12/ee552/proteus/pdk/proteus/qdi_vc_ta.lib"
set IMAGE_LIBS "/home/scf-12/ee552/proteus/pdk/proteus/qdi_image_ta.lib"
set PHYSICAL_LIBS "/home/scf-12/ee552/proteus/pdk/proteus/qdi_vc_ta.lib"
set user_scripts_dir .
set BLK_TCL /home/scf-30/huayufu/acc/acc.qdi
set RC_DEBUG false
