set PDK_ROOT /home/scf-12/ee552/proteus/pdk
set SCRIPTS /home/scf-12/ee552/proteus/scripts
set TB /home/scf-12/ee552/proteus/scripts/testbench_template
set PROTEUS /home/scf-12/ee552/proteus/bin/ClockFree
set MAX_ECO_PLACE_ITER 0
set MAX_ECO_ROUTE_ITER 0
set MAX_ECO_BLC_ITER 0
set SOC_VERSION "71"
set DO_SCAN 0
set RESTORE 0
set FIX_BUG13448 1
