
// Generated by Cadence Encounter(R) RTL Compiler v08.10-s108_1

module acc(\A_d[0][15] , \A_d[0][14] , \A_d[0][13] , \A_d[0][12] ,
     \A_d[0][11] , \A_d[0][10] , \A_d[0][9] , \A_d[0][8] , \A_d[0][7] ,
     \A_d[0][6] , \A_d[0][5] , \A_d[0][4] , \A_d[0][3] , \A_d[0][2] ,
     \A_d[0][1] , \A_d[0][0] , \A_d[1][15] , \A_d[1][14] , \A_d[1][13]
     , \A_d[1][12] , \A_d[1][11] , \A_d[1][10] , \A_d[1][9] ,
     \A_d[1][8] , \A_d[1][7] , \A_d[1][6] , \A_d[1][5] , \A_d[1][4] ,
     \A_d[1][3] , \A_d[1][2] , \A_d[1][1] , \A_d[1][0] , \A_e[15] ,
     \A_e[14] , \A_e[13] , \A_e[12] , \A_e[11] , \A_e[10] , \A_e[9] ,
     \A_e[8] , \A_e[7] , \A_e[6] , \A_e[5] , \A_e[4] , \A_e[3] ,
     \A_e[2] , \A_e[1] , \A_e[0] , \Sum_d[0][15] , \Sum_d[0][14] ,
     \Sum_d[0][13] , \Sum_d[0][12] , \Sum_d[0][11] , \Sum_d[0][10] ,
     \Sum_d[0][9] , \Sum_d[0][8] , \Sum_d[0][7] , \Sum_d[0][6] ,
     \Sum_d[0][5] , \Sum_d[0][4] , \Sum_d[0][3] , \Sum_d[0][2] ,
     \Sum_d[0][1] , \Sum_d[0][0] , \Sum_d[1][15] , \Sum_d[1][14] ,
     \Sum_d[1][13] , \Sum_d[1][12] , \Sum_d[1][11] , \Sum_d[1][10] ,
     \Sum_d[1][9] , \Sum_d[1][8] , \Sum_d[1][7] , \Sum_d[1][6] ,
     \Sum_d[1][5] , \Sum_d[1][4] , \Sum_d[1][3] , \Sum_d[1][2] ,
     \Sum_d[1][1] , \Sum_d[1][0] , \Sum_e[15] , \Sum_e[14] , \Sum_e[13]
     , \Sum_e[12] , \Sum_e[11] , \Sum_e[10] , \Sum_e[9] , \Sum_e[8] ,
     \Sum_e[7] , \Sum_e[6] , \Sum_e[5] , \Sum_e[4] , \Sum_e[3] ,
     \Sum_e[2] , \Sum_e[1] , \Sum_e[0] , CLK, _RESET);
  input \A_d[0][15] , \A_d[0][14] , \A_d[0][13] , \A_d[0][12] ,
       \A_d[0][11] , \A_d[0][10] , \A_d[0][9] , \A_d[0][8] , \A_d[0][7]
       , \A_d[0][6] , \A_d[0][5] , \A_d[0][4] , \A_d[0][3] , \A_d[0][2]
       , \A_d[0][1] , \A_d[0][0] ;
  input \A_d[1][15] , \A_d[1][14] , \A_d[1][13] , \A_d[1][12] ,
       \A_d[1][11] , \A_d[1][10] , \A_d[1][9] , \A_d[1][8] , \A_d[1][7]
       , \A_d[1][6] , \A_d[1][5] , \A_d[1][4] , \A_d[1][3] , \A_d[1][2]
       , \A_d[1][1] , \A_d[1][0] ;
  input \Sum_e[15] , \Sum_e[14] , \Sum_e[13] , \Sum_e[12] , \Sum_e[11]
       , \Sum_e[10] , \Sum_e[9] , \Sum_e[8] , \Sum_e[7] , \Sum_e[6] ,
       \Sum_e[5] , \Sum_e[4] , \Sum_e[3] , \Sum_e[2] , \Sum_e[1] ,
       \Sum_e[0] ;
  input CLK, _RESET;
  output \A_e[15] , \A_e[14] , \A_e[13] , \A_e[12] , \A_e[11] ,
       \A_e[10] , \A_e[9] , \A_e[8] , \A_e[7] , \A_e[6] , \A_e[5] ,
       \A_e[4] , \A_e[3] , \A_e[2] , \A_e[1] , \A_e[0] ;
  output \Sum_d[0][15] , \Sum_d[0][14] , \Sum_d[0][13] , \Sum_d[0][12]
       , \Sum_d[0][11] , \Sum_d[0][10] , \Sum_d[0][9] , \Sum_d[0][8] ,
       \Sum_d[0][7] , \Sum_d[0][6] , \Sum_d[0][5] , \Sum_d[0][4] ,
       \Sum_d[0][3] , \Sum_d[0][2] , \Sum_d[0][1] , \Sum_d[0][0] ;
  output \Sum_d[1][15] , \Sum_d[1][14] , \Sum_d[1][13] , \Sum_d[1][12]
       , \Sum_d[1][11] , \Sum_d[1][10] , \Sum_d[1][9] , \Sum_d[1][8] ,
       \Sum_d[1][7] , \Sum_d[1][6] , \Sum_d[1][5] , \Sum_d[1][4] ,
       \Sum_d[1][3] , \Sum_d[1][2] , \Sum_d[1][1] , \Sum_d[1][0] ;
  wire \A_d[0][15] , \A_d[0][14] , \A_d[0][13] , \A_d[0][12] ,
       \A_d[0][11] , \A_d[0][10] , \A_d[0][9] , \A_d[0][8] , \A_d[0][7]
       , \A_d[0][6] , \A_d[0][5] , \A_d[0][4] , \A_d[0][3] , \A_d[0][2]
       , \A_d[0][1] , \A_d[0][0] ;
  wire \A_d[1][15] , \A_d[1][14] , \A_d[1][13] , \A_d[1][12] ,
       \A_d[1][11] , \A_d[1][10] , \A_d[1][9] , \A_d[1][8] , \A_d[1][7]
       , \A_d[1][6] , \A_d[1][5] , \A_d[1][4] , \A_d[1][3] , \A_d[1][2]
       , \A_d[1][1] , \A_d[1][0] ;
  wire \Sum_e[15] , \Sum_e[14] , \Sum_e[13] , \Sum_e[12] , \Sum_e[11] ,
       \Sum_e[10] , \Sum_e[9] , \Sum_e[8] , \Sum_e[7] , \Sum_e[6] ,
       \Sum_e[5] , \Sum_e[4] , \Sum_e[3] , \Sum_e[2] , \Sum_e[1] ,
       \Sum_e[0] ;
  wire CLK, _RESET;
  wire \A_e[15] , \A_e[14] , \A_e[13] , \A_e[12] , \A_e[11] , \A_e[10]
       , \A_e[9] , \A_e[8] , \A_e[7] , \A_e[6] , \A_e[5] , \A_e[4] ,
       \A_e[3] , \A_e[2] , \A_e[1] , \A_e[0] ;
  wire \Sum_d[0][15] , \Sum_d[0][14] , \Sum_d[0][13] , \Sum_d[0][12] ,
       \Sum_d[0][11] , \Sum_d[0][10] , \Sum_d[0][9] , \Sum_d[0][8] ,
       \Sum_d[0][7] , \Sum_d[0][6] , \Sum_d[0][5] , \Sum_d[0][4] ,
       \Sum_d[0][3] , \Sum_d[0][2] , \Sum_d[0][1] , \Sum_d[0][0] ;
  wire \Sum_d[1][15] , \Sum_d[1][14] , \Sum_d[1][13] , \Sum_d[1][12] ,
       \Sum_d[1][11] , \Sum_d[1][10] , \Sum_d[1][9] , \Sum_d[1][8] ,
       \Sum_d[1][7] , \Sum_d[1][6] , \Sum_d[1][5] , \Sum_d[1][4] ,
       \Sum_d[1][3] , \Sum_d[1][2] , \Sum_d[1][1] , \Sum_d[1][0] ;
  wire \acc_RTL_BODY.add_28_30.n_2 , \acc_RTL_BODY.add_28_30.n_3 ,
       \acc_RTL_BODY.add_28_30.n_4 , \acc_RTL_BODY.add_28_30.n_6 ,
       \acc_RTL_BODY.add_28_30.n_7 , \acc_RTL_BODY.add_28_30.n_9 ,
       \acc_RTL_BODY.add_28_30.n_10 , \acc_RTL_BODY.add_28_30.n_11 ;
  wire \acc_RTL_BODY.add_28_30.n_12 , \acc_RTL_BODY.add_28_30.n_13 ,
       \acc_RTL_BODY.add_28_30.n_14 , \acc_RTL_BODY.add_28_30.n_15 ,
       \acc_RTL_BODY.add_28_30.n_16 , \acc_RTL_BODY.add_28_30.n_17 ,
       \acc_RTL_BODY.add_28_30.n_18 , \acc_RTL_BODY.add_28_30.n_19 ;
  wire \acc_RTL_BODY.add_28_30.n_20 , \acc_RTL_BODY.add_28_30.n_22 ,
       \acc_RTL_BODY.add_28_30.n_23 , \acc_RTL_BODY.add_28_30.n_24 ,
       \acc_RTL_BODY.add_28_30.n_25 , \acc_RTL_BODY.add_28_30.n_26 ,
       \acc_RTL_BODY.add_28_30.n_27 , \acc_RTL_BODY.add_28_30.n_28 ;
  wire \acc_RTL_BODY.add_28_30.n_29 , \acc_RTL_BODY.add_28_30.n_30 ,
       \acc_RTL_BODY.add_28_30.n_32 , \acc_RTL_BODY.add_28_30.n_35 ,
       \acc_RTL_BODY.add_28_30.n_37 , \acc_RTL_BODY.add_28_30.n_38 ,
       \acc_RTL_BODY.add_28_30.n_40 , \acc_RTL_BODY.add_28_30.n_41 ;
  wire \acc_RTL_BODY.add_28_30.n_42 , \acc_RTL_BODY.add_28_30.n_43 ,
       \acc_RTL_BODY.add_28_30.n_46 , \acc_RTL_BODY.add_28_30.n_47 ,
       \acc_RTL_BODY.add_28_30.n_48 , \acc_RTL_BODY.add_28_30.n_49 ,
       \acc_RTL_BODY.add_28_30.n_51 , \acc_RTL_BODY.add_28_30.n_52 ;
  wire \acc_RTL_BODY.add_28_30.n_53 , \acc_RTL_BODY.add_28_30.n_54 ,
       \acc_RTL_BODY.add_28_30.n_56 , \acc_RTL_BODY.add_28_30.n_57 ,
       \acc_RTL_BODY.add_28_30.n_58 , \acc_RTL_BODY.add_28_30.n_61 ,
       \acc_RTL_BODY.add_28_30.n_62 , \acc_RTL_BODY.add_28_30.n_63 ;
  wire \acc_RTL_BODY.add_28_30.n_64 , \acc_RTL_BODY.add_28_30.n_66 ,
       \acc_RTL_BODY.add_28_30.n_67 , \acc_RTL_BODY.add_28_30.n_106 ,
       \acc_RTL_BODY.add_28_30.n_109 , \acc_RTL_BODY.add_28_30.n_111 ,
       \acc_RTL_BODY.sum[0] , \acc_RTL_BODY.sum[1] ;
  wire \acc_RTL_BODY.sum[2] , \acc_RTL_BODY.sum[3] ,
       \acc_RTL_BODY.sum[4] , \acc_RTL_BODY.sum[5] ,
       \acc_RTL_BODY.sum[6] , \acc_RTL_BODY.sum[7] ,
       \acc_RTL_BODY.sum[8] , \acc_RTL_BODY.sum[9] ;
  wire \acc_RTL_BODY.sum[10] , \acc_RTL_BODY.sum[11] ,
       \acc_RTL_BODY.sum[12] , \acc_RTL_BODY.sum[13] ,
       \acc_RTL_BODY.sum[14] , \acc_RTL_BODY.sum[15] , \d[0] , \d[1] ;
  wire \d[2] , \d[3] , \d[4] , \d[5] , \d[6] , \d[7] , \d[8] , \d[9] ;
  wire \d[10] , \d[11] , \d[12] , \d[13] , \d[14] , \d[15] , n_40, n_41;
  wire n_42, n_43, n_44, n_45, n_46, n_47, n_48, n_50;
  wire n_51, n_52, n_53, n_54, n_55, n_56;
  TOK_BUF_X6 \acc_RTL_BODY.ff$sum_reg[0] (.RN (_RESET), .SN (1'b1), .CK
       (CLK), .L (n_56), .R (\acc_RTL_BODY.sum[0] ));
  TOK_BUF_X6 \acc_RTL_BODY.ff$sum_reg[10] (.RN (_RESET), .SN (1'b1),
       .CK (CLK), .L (n_45), .R (\acc_RTL_BODY.sum[10] ));
  TOK_BUF_X6 \acc_RTL_BODY.ff$sum_reg[11] (.RN (_RESET), .SN (1'b1),
       .CK (CLK), .L (n_44), .R (\acc_RTL_BODY.sum[11] ));
  TOK_BUF_X6 \acc_RTL_BODY.ff$sum_reg[12] (.RN (_RESET), .SN (1'b1),
       .CK (CLK), .L (n_43), .R (\acc_RTL_BODY.sum[12] ));
  TOK_BUF_X6 \acc_RTL_BODY.ff$sum_reg[13] (.RN (_RESET), .SN (1'b1),
       .CK (CLK), .L (n_42), .R (\acc_RTL_BODY.sum[13] ));
  TOK_BUF_X6 \acc_RTL_BODY.ff$sum_reg[5] (.RN (_RESET), .SN (1'b1), .CK
       (CLK), .L (n_51), .R (\acc_RTL_BODY.sum[5] ));
  TOK_BUF_X6 \acc_RTL_BODY.ff$sum_reg[14] (.RN (_RESET), .SN (1'b1),
       .CK (CLK), .L (n_41), .R (\acc_RTL_BODY.sum[14] ));
  TOK_BUF_X6 \acc_RTL_BODY.ff$sum_reg[15] (.RN (_RESET), .SN (1'b1),
       .CK (CLK), .L (n_40), .R (\acc_RTL_BODY.sum[15] ));
  TOK_BUF_X6 \acc_RTL_BODY.ff$sum_reg[1] (.RN (_RESET), .SN (1'b1), .CK
       (CLK), .L (n_55), .R (\acc_RTL_BODY.sum[1] ));
  TOK_BUF_X6 \acc_RTL_BODY.ff$sum_reg[2] (.RN (_RESET), .SN (1'b1), .CK
       (CLK), .L (n_54), .R (\acc_RTL_BODY.sum[2] ));
  TOK_BUF_X6 \acc_RTL_BODY.ff$sum_reg[3] (.RN (_RESET), .SN (1'b1), .CK
       (CLK), .L (n_53), .R (\acc_RTL_BODY.sum[3] ));
  TOK_BUF_X6 \acc_RTL_BODY.ff$sum_reg[4] (.RN (_RESET), .SN (1'b1), .CK
       (CLK), .L (n_52), .R (\acc_RTL_BODY.sum[4] ));
  TOK_BUF_X6 \acc_RTL_BODY.ff$sum_reg[6] (.RN (_RESET), .SN (1'b1), .CK
       (CLK), .L (n_50), .R (\acc_RTL_BODY.sum[6] ));
  TOK_BUF_X6 \acc_RTL_BODY.ff$sum_reg[7] (.RN (_RESET), .SN (1'b1), .CK
       (CLK), .L (n_48), .R (\acc_RTL_BODY.sum[7] ));
  TOK_BUF_X6 \acc_RTL_BODY.ff$sum_reg[8] (.RN (_RESET), .SN (1'b1), .CK
       (CLK), .L (n_47), .R (\acc_RTL_BODY.sum[8] ));
  TOK_BUF_X6 \acc_RTL_BODY.ff$sum_reg[9] (.RN (_RESET), .SN (1'b1), .CK
       (CLK), .L (n_46), .R (\acc_RTL_BODY.sum[9] ));
  LOGIC3_96_X4 \acc_RTL_BODY.add_28_30.g19121 (.A0 (\d[13] ), .A1
       (\acc_RTL_BODY.sum[13] ), .A2 (\acc_RTL_BODY.add_28_30.n_66 ),
       .X (n_42));
  LOGIC3_96_X4 \acc_RTL_BODY.add_28_30.g19122 (.A0 (\d[9] ), .A1
       (\acc_RTL_BODY.sum[9] ), .A2 (\acc_RTL_BODY.add_28_30.n_67 ), .X
       (n_46));
  LOGIC4_FF1F_X2 \acc_RTL_BODY.add_28_30.g19123 (.A0
       (\acc_RTL_BODY.add_28_30.n_106 ), .A1
       (\acc_RTL_BODY.add_28_30.n_63 ), .A2
       (\acc_RTL_BODY.add_28_30.n_61 ), .A3
       (\acc_RTL_BODY.add_28_30.n_38 ), .X (n_40));
  LOGIC4_FF1F_X2 \acc_RTL_BODY.add_28_30.g19124 (.A0
       (\acc_RTL_BODY.add_28_30.n_37 ), .A1
       (\acc_RTL_BODY.add_28_30.n_64 ), .A2
       (\acc_RTL_BODY.add_28_30.n_62 ), .A3
       (\acc_RTL_BODY.add_28_30.n_35 ), .X (n_44));
  LOGIC3_69_X4 \acc_RTL_BODY.add_28_30.g19125 (.A0 (\d[10] ), .A1
       (\acc_RTL_BODY.sum[10] ), .A2 (\acc_RTL_BODY.add_28_30.n_64 ),
       .X (n_45));
  LOGIC3_69_X4 \acc_RTL_BODY.add_28_30.g19126 (.A0 (\d[14] ), .A1
       (\acc_RTL_BODY.sum[14] ), .A2 (\acc_RTL_BODY.add_28_30.n_63 ),
       .X (n_41));
  LOGIC5_4F44FFFF_X2 \acc_RTL_BODY.add_28_30.g19127 (.A0
       (\acc_RTL_BODY.add_28_30.n_52 ), .A1 (\d[8] ), .A2
       (\acc_RTL_BODY.add_28_30.n_52 ), .A3 (\acc_RTL_BODY.sum[8] ),
       .A4 (\acc_RTL_BODY.add_28_30.n_16 ), .X
       (\acc_RTL_BODY.add_28_30.n_67 ));
  LOGIC5_4F44FFFF_X2 \acc_RTL_BODY.add_28_30.g19128 (.A0
       (\acc_RTL_BODY.add_28_30.n_54 ), .A1 (\d[12] ), .A2
       (\acc_RTL_BODY.add_28_30.n_54 ), .A3 (\acc_RTL_BODY.sum[12] ),
       .A4 (\acc_RTL_BODY.add_28_30.n_9 ), .X
       (\acc_RTL_BODY.add_28_30.n_66 ));
  LOGIC3_96_X4 \acc_RTL_BODY.add_28_30.g19129 (.A0 (\d[7] ), .A1
       (\acc_RTL_BODY.sum[7] ), .A2 (\acc_RTL_BODY.add_28_30.n_56 ), .X
       (n_48));
  LOGIC2_2_X4 \acc_RTL_BODY.add_28_30.g19130 (.A0
       (\acc_RTL_BODY.add_28_30.n_109 ), .A1
       (\acc_RTL_BODY.add_28_30.n_58 ), .X
       (\acc_RTL_BODY.add_28_30.n_64 ));
  LOGIC2_2_X4 \acc_RTL_BODY.add_28_30.g19131 (.A0
       (\acc_RTL_BODY.add_28_30.n_29 ), .A1
       (\acc_RTL_BODY.add_28_30.n_57 ), .X
       (\acc_RTL_BODY.add_28_30.n_63 ));
  LOGIC4_FF7F_X2 \acc_RTL_BODY.add_28_30.g19132 (.A0
       (\acc_RTL_BODY.add_28_30.n_2 ), .A1
       (\acc_RTL_BODY.add_28_30.n_18 ), .A2
       (\acc_RTL_BODY.add_28_30.n_109 ), .A3
       (\acc_RTL_BODY.add_28_30.n_58 ), .X
       (\acc_RTL_BODY.add_28_30.n_62 ));
  LOGIC4_FF7F_X2 \acc_RTL_BODY.add_28_30.g19133 (.A0
       (\acc_RTL_BODY.add_28_30.n_29 ), .A1
       (\acc_RTL_BODY.add_28_30.n_17 ), .A2
       (\acc_RTL_BODY.add_28_30.n_22 ), .A3
       (\acc_RTL_BODY.add_28_30.n_57 ), .X
       (\acc_RTL_BODY.add_28_30.n_61 ));
  LOGIC3_69_X4 \acc_RTL_BODY.add_28_30.g19134 (.A0 (\d[12] ), .A1
       (\acc_RTL_BODY.sum[12] ), .A2 (\acc_RTL_BODY.add_28_30.n_54 ),
       .X (n_43));
  LOGIC3_69_X4 \acc_RTL_BODY.add_28_30.g19135 (.A0 (\d[8] ), .A1
       (\acc_RTL_BODY.sum[8] ), .A2 (\acc_RTL_BODY.add_28_30.n_52 ), .X
       (n_47));
  LOGIC2_2_X4 \acc_RTL_BODY.add_28_30.g19136 (.A0
       (\acc_RTL_BODY.add_28_30.n_24 ), .A1
       (\acc_RTL_BODY.add_28_30.n_51 ), .X
       (\acc_RTL_BODY.add_28_30.n_58 ));
  LOGIC4_000E_X2 \acc_RTL_BODY.add_28_30.g19137 (.A0 (\d[12] ), .A1
       (\acc_RTL_BODY.sum[12] ), .A2 (\acc_RTL_BODY.add_28_30.n_11 ),
       .A3 (\acc_RTL_BODY.add_28_30.n_53 ), .X
       (\acc_RTL_BODY.add_28_30.n_57 ));
  LOGIC5_4F44FFFF_X2 \acc_RTL_BODY.add_28_30.g19138 (.A0
       (\acc_RTL_BODY.add_28_30.n_47 ), .A1 (\d[6] ), .A2
       (\acc_RTL_BODY.add_28_30.n_47 ), .A3 (\acc_RTL_BODY.sum[6] ),
       .A4 (\acc_RTL_BODY.add_28_30.n_13 ), .X
       (\acc_RTL_BODY.add_28_30.n_56 ));
  LOGIC3_96_X4 \acc_RTL_BODY.add_28_30.g19139 (.A0 (\d[5] ), .A1
       (\acc_RTL_BODY.sum[5] ), .A2 (\acc_RTL_BODY.add_28_30.n_48 ), .X
       (n_51));
  BUF_X1 \acc_RTL_BODY.add_28_30.g19140 (.L
       (\acc_RTL_BODY.add_28_30.n_53 ), .R
       (\acc_RTL_BODY.add_28_30.n_54 ));
  LOGIC4_0007_X2 \acc_RTL_BODY.add_28_30.g19141 (.A0
       (\acc_RTL_BODY.add_28_30.n_27 ), .A1
       (\acc_RTL_BODY.add_28_30.n_42 ), .A2
       (\acc_RTL_BODY.add_28_30.n_30 ), .A3
       (\acc_RTL_BODY.add_28_30.n_49 ), .X
       (\acc_RTL_BODY.add_28_30.n_53 ));
  BUF_X1 \acc_RTL_BODY.add_28_30.g19142 (.L
       (\acc_RTL_BODY.add_28_30.n_51 ), .R
       (\acc_RTL_BODY.add_28_30.n_52 ));
  LOGIC3_0B_X4 \acc_RTL_BODY.add_28_30.g19143 (.A0
       (\acc_RTL_BODY.add_28_30.n_47 ), .A1
       (\acc_RTL_BODY.add_28_30.n_26 ), .A2
       (\acc_RTL_BODY.add_28_30.n_111 ), .X
       (\acc_RTL_BODY.add_28_30.n_51 ));
  LOGIC3_69_X4 \acc_RTL_BODY.add_28_30.g19144 (.A0 (\d[6] ), .A1
       (\acc_RTL_BODY.sum[6] ), .A2 (\acc_RTL_BODY.add_28_30.n_47 ), .X
       (n_50));
  LOGIC4_0080_X2 \acc_RTL_BODY.add_28_30.g19145 (.A0
       (\acc_RTL_BODY.add_28_30.n_24 ), .A1
       (\acc_RTL_BODY.add_28_30.n_26 ), .A2
       (\acc_RTL_BODY.add_28_30.n_27 ), .A3
       (\acc_RTL_BODY.add_28_30.n_46 ), .X
       (\acc_RTL_BODY.add_28_30.n_49 ));
  LOGIC5_4F44FFFF_X2 \acc_RTL_BODY.add_28_30.g19146 (.A0
       (\acc_RTL_BODY.add_28_30.n_41 ), .A1 (\d[4] ), .A2
       (\acc_RTL_BODY.add_28_30.n_41 ), .A3 (\acc_RTL_BODY.sum[4] ),
       .A4 (\acc_RTL_BODY.add_28_30.n_15 ), .X
       (\acc_RTL_BODY.add_28_30.n_48 ));
  BUF_X1 \acc_RTL_BODY.add_28_30.g19148 (.L
       (\acc_RTL_BODY.add_28_30.n_46 ), .R
       (\acc_RTL_BODY.add_28_30.n_47 ));
  LOGIC6_0000B0BBB0BBB0BB_X2 \acc_RTL_BODY.add_28_30.g19149 (.A0
       (\acc_RTL_BODY.add_28_30.n_40 ), .A1
       (\acc_RTL_BODY.add_28_30.n_25 ), .A2
       (\acc_RTL_BODY.add_28_30.n_15 ), .A3
       (\acc_RTL_BODY.add_28_30.n_10 ), .A4 (\d[5] ), .A5
       (\acc_RTL_BODY.sum[5] ), .X (\acc_RTL_BODY.add_28_30.n_46 ));
  LOGIC3_69_X4 \acc_RTL_BODY.add_28_30.g19150 (.A0 (\d[4] ), .A1
       (\acc_RTL_BODY.sum[4] ), .A2 (\acc_RTL_BODY.add_28_30.n_41 ), .X
       (n_52));
  LOGIC3_96_X4 \acc_RTL_BODY.add_28_30.g19151 (.A0 (\d[3] ), .A1
       (\acc_RTL_BODY.sum[3] ), .A2 (\acc_RTL_BODY.add_28_30.n_43 ), .X
       (n_53));
  LOGIC3_1F_X4 \acc_RTL_BODY.add_28_30.g19152 (.A0
       (\acc_RTL_BODY.add_28_30.n_19 ), .A1
       (\acc_RTL_BODY.add_28_30.n_28 ), .A2
       (\acc_RTL_BODY.add_28_30.n_12 ), .X
       (\acc_RTL_BODY.add_28_30.n_43 ));
  LOGIC3_8F_X4 \acc_RTL_BODY.add_28_30.g19153 (.A0
       (\acc_RTL_BODY.add_28_30.n_24 ), .A1
       (\acc_RTL_BODY.add_28_30.n_111 ), .A2
       (\acc_RTL_BODY.add_28_30.n_109 ), .X
       (\acc_RTL_BODY.add_28_30.n_42 ));
  BUF_X1 \acc_RTL_BODY.add_28_30.g19154 (.L
       (\acc_RTL_BODY.add_28_30.n_40 ), .R
       (\acc_RTL_BODY.add_28_30.n_41 ));
  LOGIC4_00EF_X4 \acc_RTL_BODY.add_28_30.g19155 (.A0
       (\acc_RTL_BODY.add_28_30.n_19 ), .A1
       (\acc_RTL_BODY.add_28_30.n_28 ), .A2
       (\acc_RTL_BODY.add_28_30.n_6 ), .A3
       (\acc_RTL_BODY.add_28_30.n_32 ), .X
       (\acc_RTL_BODY.add_28_30.n_40 ));
  LOGIC3_69_X4 \acc_RTL_BODY.add_28_30.g19156 (.A0 (\d[2] ), .A1
       (\acc_RTL_BODY.sum[2] ), .A2 (\acc_RTL_BODY.add_28_30.n_28 ), .X
       (n_54));
  LOGIC3_19_X4 \acc_RTL_BODY.add_28_30.g19157 (.A0
       (\acc_RTL_BODY.add_28_30.n_17 ), .A1
       (\acc_RTL_BODY.add_28_30.n_22 ), .A2
       (\acc_RTL_BODY.add_28_30.n_20 ), .X
       (\acc_RTL_BODY.add_28_30.n_38 ));
  LOGIC4_F351_X4 \acc_RTL_BODY.add_28_30.g19158 (.A0 (\d[10] ), .A1
       (\acc_RTL_BODY.sum[10] ), .A2 (\acc_RTL_BODY.add_28_30.n_23 ),
       .A3 (\acc_RTL_BODY.add_28_30.n_2 ), .X
       (\acc_RTL_BODY.add_28_30.n_37 ));
  LOGIC3_19_X4 \acc_RTL_BODY.add_28_30.g19160 (.A0
       (\acc_RTL_BODY.add_28_30.n_23 ), .A1
       (\acc_RTL_BODY.add_28_30.n_18 ), .A2
       (\acc_RTL_BODY.add_28_30.n_4 ), .X (\acc_RTL_BODY.add_28_30.n_35
       ));
  LOGIC3_96_X4 \acc_RTL_BODY.add_28_30.g19161 (.A0 (\d[1] ), .A1
       (\acc_RTL_BODY.sum[1] ), .A2 (\acc_RTL_BODY.add_28_30.n_7 ), .X
       (n_55));
  LOGIC4_C0EA_X4 \acc_RTL_BODY.add_28_30.g19163 (.A0
       (\acc_RTL_BODY.add_28_30.n_6 ), .A1 (\acc_RTL_BODY.sum[3] ), .A2
       (\d[3] ), .A3 (\acc_RTL_BODY.add_28_30.n_12 ), .X
       (\acc_RTL_BODY.add_28_30.n_32 ));
  LOGIC4_C0D5_X4 \acc_RTL_BODY.add_28_30.g19165 (.A0
       (\acc_RTL_BODY.add_28_30.n_18 ), .A1 (\acc_RTL_BODY.sum[11] ),
       .A2 (\d[11] ), .A3 (\acc_RTL_BODY.add_28_30.n_14 ), .X
       (\acc_RTL_BODY.add_28_30.n_30 ));
  LOGIC4_3F2A_X4 \acc_RTL_BODY.add_28_30.g19166 (.A0
       (\acc_RTL_BODY.add_28_30.n_9 ), .A1 (\acc_RTL_BODY.sum[13] ),
       .A2 (\d[13] ), .A3 (\acc_RTL_BODY.add_28_30.n_11 ), .X
       (\acc_RTL_BODY.add_28_30.n_29 ));
  LOGIC3_17_X4 \acc_RTL_BODY.add_28_30.g19167 (.A0
       (\acc_RTL_BODY.add_28_30.n_7 ), .A1 (\d[1] ), .A2
       (\acc_RTL_BODY.sum[1] ), .X (\acc_RTL_BODY.add_28_30.n_28 ));
  LOGIC2_2_X4 \acc_RTL_BODY.add_28_30.g19168 (.A0
       (\acc_RTL_BODY.add_28_30.n_4 ), .A1
       (\acc_RTL_BODY.add_28_30.n_14 ), .X
       (\acc_RTL_BODY.add_28_30.n_27 ));
  LOGIC4_FCA8_X4 \acc_RTL_BODY.add_28_30.g19169 (.A0 (\d[7] ), .A1
       (\acc_RTL_BODY.sum[6] ), .A2 (\d[6] ), .A3 (\acc_RTL_BODY.sum[7]
       ), .X (\acc_RTL_BODY.add_28_30.n_26 ));
  LOGIC4_FCA8_X4 \acc_RTL_BODY.add_28_30.g19170 (.A0 (\d[5] ), .A1
       (\acc_RTL_BODY.sum[4] ), .A2 (\d[4] ), .A3 (\acc_RTL_BODY.sum[5]
       ), .X (\acc_RTL_BODY.add_28_30.n_25 ));
  LOGIC4_FCA8_X4 \acc_RTL_BODY.add_28_30.g19171 (.A0 (\d[9] ), .A1
       (\acc_RTL_BODY.sum[8] ), .A2 (\d[8] ), .A3 (\acc_RTL_BODY.sum[9]
       ), .X (\acc_RTL_BODY.add_28_30.n_24 ));
  LOGIC2_6_X4 \acc_RTL_BODY.add_28_30.g19172 (.A0 (\d[11] ), .A1
       (\acc_RTL_BODY.sum[11] ), .X (\acc_RTL_BODY.add_28_30.n_23 ));
  LOGIC2_6_X4 \acc_RTL_BODY.add_28_30.g19173 (.A0 (\d[15] ), .A1
       (\acc_RTL_BODY.sum[15] ), .X (\acc_RTL_BODY.add_28_30.n_22 ));
  LOGIC2_6_X4 \acc_RTL_BODY.add_28_30.g19174 (.A0 (\d[0] ), .A1
       (\acc_RTL_BODY.sum[0] ), .X (n_56));
  LOGIC2_E_X4 \acc_RTL_BODY.add_28_30.g19175 (.A0
       (\acc_RTL_BODY.sum[14] ), .A1 (\d[14] ), .X
       (\acc_RTL_BODY.add_28_30.n_20 ));
  LOGIC2_1_X4 \acc_RTL_BODY.add_28_30.g19176 (.A0 (\acc_RTL_BODY.sum[2]
       ), .A1 (\d[2] ), .X (\acc_RTL_BODY.add_28_30.n_19 ));
  LOGIC2_7_X4 \acc_RTL_BODY.add_28_30.g19177 (.A0
       (\acc_RTL_BODY.sum[10] ), .A1 (\d[10] ), .X
       (\acc_RTL_BODY.add_28_30.n_18 ));
  LOGIC2_7_X4 \acc_RTL_BODY.add_28_30.g19178 (.A0
       (\acc_RTL_BODY.sum[14] ), .A1 (\d[14] ), .X
       (\acc_RTL_BODY.add_28_30.n_17 ));
  LOGIC2_7_X4 \acc_RTL_BODY.add_28_30.g19179 (.A0 (\acc_RTL_BODY.sum[8]
       ), .A1 (\d[8] ), .X (\acc_RTL_BODY.add_28_30.n_16 ));
  LOGIC2_7_X4 \acc_RTL_BODY.add_28_30.g19180 (.A0 (\acc_RTL_BODY.sum[4]
       ), .A1 (\d[4] ), .X (\acc_RTL_BODY.add_28_30.n_15 ));
  LOGIC2_1_X4 \acc_RTL_BODY.add_28_30.g19181 (.A0
       (\acc_RTL_BODY.sum[11] ), .A1 (\d[11] ), .X
       (\acc_RTL_BODY.add_28_30.n_14 ));
  LOGIC2_7_X4 \acc_RTL_BODY.add_28_30.g19182 (.A0 (\acc_RTL_BODY.sum[6]
       ), .A1 (\d[6] ), .X (\acc_RTL_BODY.add_28_30.n_13 ));
  LOGIC2_7_X4 \acc_RTL_BODY.add_28_30.g19183 (.A0 (\acc_RTL_BODY.sum[2]
       ), .A1 (\d[2] ), .X (\acc_RTL_BODY.add_28_30.n_12 ));
  LOGIC2_1_X4 \acc_RTL_BODY.add_28_30.g19184 (.A0
       (\acc_RTL_BODY.sum[13] ), .A1 (\d[13] ), .X
       (\acc_RTL_BODY.add_28_30.n_11 ));
  LOGIC2_E_X4 \acc_RTL_BODY.add_28_30.g19185 (.A0 (\acc_RTL_BODY.sum[5]
       ), .A1 (\d[5] ), .X (\acc_RTL_BODY.add_28_30.n_10 ));
  LOGIC2_7_X4 \acc_RTL_BODY.add_28_30.g19186 (.A0
       (\acc_RTL_BODY.sum[12] ), .A1 (\d[12] ), .X
       (\acc_RTL_BODY.add_28_30.n_9 ));
  LOGIC2_8_X4 \acc_RTL_BODY.add_28_30.g19188 (.A0 (\acc_RTL_BODY.sum[0]
       ), .A1 (\d[0] ), .X (\acc_RTL_BODY.add_28_30.n_7 ));
  LOGIC2_E_X4 \acc_RTL_BODY.add_28_30.g19189 (.A0 (\acc_RTL_BODY.sum[3]
       ), .A1 (\d[3] ), .X (\acc_RTL_BODY.add_28_30.n_6 ));
  LOGIC2_E_X4 \acc_RTL_BODY.add_28_30.g19191 (.A0
       (\acc_RTL_BODY.sum[10] ), .A1 (\d[10] ), .X
       (\acc_RTL_BODY.add_28_30.n_4 ));
  INV_X1 \acc_RTL_BODY.add_28_30.g19193 (.L
       (\acc_RTL_BODY.add_28_30.n_3 ), .R (\acc_RTL_BODY.add_28_30.n_2
       ));
  INV_X1 \acc_RTL_BODY.add_28_30.g19194 (.L
       (\acc_RTL_BODY.add_28_30.n_23 ), .R (\acc_RTL_BODY.add_28_30.n_3
       ));
  LOGIC3_F1_X4 \acc_RTL_BODY.add_28_30.g2 (.A0 (\d[14] ), .A1
       (\acc_RTL_BODY.sum[14] ), .A2 (\acc_RTL_BODY.add_28_30.n_22 ),
       .X (\acc_RTL_BODY.add_28_30.n_106 ));
  LOGIC3_2B_X4 \acc_RTL_BODY.add_28_30.g19203 (.A0
       (\acc_RTL_BODY.add_28_30.n_16 ), .A1 (\acc_RTL_BODY.sum[9] ),
       .A2 (\d[9] ), .X (\acc_RTL_BODY.add_28_30.n_109 ));
  LOGIC3_8E_X4 \acc_RTL_BODY.add_28_30.g19206 (.A0
       (\acc_RTL_BODY.sum[7] ), .A1 (\d[7] ), .A2
       (\acc_RTL_BODY.add_28_30.n_13 ), .X
       (\acc_RTL_BODY.add_28_30.n_111 ));
  SEND_1of2_X2 \Sum_SEND.send.bits[0].send (.\R.e  (\Sum_e[0] ), .E
       (1'b1), .\L[0]  (n_56), .\R.0  (\Sum_d[0][0] ), .\R.1 
       (\Sum_d[1][0] ));
  SEND_1of2_X2 \Sum_SEND.send.bits[10].send (.\R.e  (\Sum_e[10] ), .E
       (1'b1), .\L[0]  (n_45), .\R.0  (\Sum_d[0][10] ), .\R.1 
       (\Sum_d[1][10] ));
  SEND_1of2_X2 \Sum_SEND.send.bits[11].send (.\R.e  (\Sum_e[11] ), .E
       (1'b1), .\L[0]  (n_44), .\R.0  (\Sum_d[0][11] ), .\R.1 
       (\Sum_d[1][11] ));
  SEND_1of2_X2 \Sum_SEND.send.bits[12].send (.\R.e  (\Sum_e[12] ), .E
       (1'b1), .\L[0]  (n_43), .\R.0  (\Sum_d[0][12] ), .\R.1 
       (\Sum_d[1][12] ));
  SEND_1of2_X2 \Sum_SEND.send.bits[13].send (.\R.e  (\Sum_e[13] ), .E
       (1'b1), .\L[0]  (n_42), .\R.0  (\Sum_d[0][13] ), .\R.1 
       (\Sum_d[1][13] ));
  SEND_1of2_X2 \Sum_SEND.send.bits[14].send (.\R.e  (\Sum_e[14] ), .E
       (1'b1), .\L[0]  (n_41), .\R.0  (\Sum_d[0][14] ), .\R.1 
       (\Sum_d[1][14] ));
  SEND_1of2_X2 \Sum_SEND.send.bits[15].send (.\R.e  (\Sum_e[15] ), .E
       (1'b1), .\L[0]  (n_40), .\R.0  (\Sum_d[0][15] ), .\R.1 
       (\Sum_d[1][15] ));
  SEND_1of2_X2 \Sum_SEND.send.bits[1].send (.\R.e  (\Sum_e[1] ), .E
       (1'b1), .\L[0]  (n_55), .\R.0  (\Sum_d[0][1] ), .\R.1 
       (\Sum_d[1][1] ));
  SEND_1of2_X2 \Sum_SEND.send.bits[2].send (.\R.e  (\Sum_e[2] ), .E
       (1'b1), .\L[0]  (n_54), .\R.0  (\Sum_d[0][2] ), .\R.1 
       (\Sum_d[1][2] ));
  SEND_1of2_X2 \Sum_SEND.send.bits[3].send (.\R.e  (\Sum_e[3] ), .E
       (1'b1), .\L[0]  (n_53), .\R.0  (\Sum_d[0][3] ), .\R.1 
       (\Sum_d[1][3] ));
  SEND_1of2_X2 \Sum_SEND.send.bits[4].send (.\R.e  (\Sum_e[4] ), .E
       (1'b1), .\L[0]  (n_52), .\R.0  (\Sum_d[0][4] ), .\R.1 
       (\Sum_d[1][4] ));
  SEND_1of2_X2 \Sum_SEND.send.bits[5].send (.\R.e  (\Sum_e[5] ), .E
       (1'b1), .\L[0]  (n_51), .\R.0  (\Sum_d[0][5] ), .\R.1 
       (\Sum_d[1][5] ));
  SEND_1of2_X2 \Sum_SEND.send.bits[6].send (.\R.e  (\Sum_e[6] ), .E
       (1'b1), .\L[0]  (n_50), .\R.0  (\Sum_d[0][6] ), .\R.1 
       (\Sum_d[1][6] ));
  SEND_1of2_X2 \Sum_SEND.send.bits[7].send (.\R.e  (\Sum_e[7] ), .E
       (1'b1), .\L[0]  (n_48), .\R.0  (\Sum_d[0][7] ), .\R.1 
       (\Sum_d[1][7] ));
  SEND_1of2_X2 \Sum_SEND.send.bits[8].send (.\R.e  (\Sum_e[8] ), .E
       (1'b1), .\L[0]  (n_47), .\R.0  (\Sum_d[0][8] ), .\R.1 
       (\Sum_d[1][8] ));
  SEND_1of2_X2 \Sum_SEND.send.bits[9].send (.\R.e  (\Sum_e[9] ), .E
       (1'b1), .\L[0]  (n_46), .\R.0  (\Sum_d[0][9] ), .\R.1 
       (\Sum_d[1][9] ));
  RECV_1of2_X2 \A_RECEIVE.recv.bits[0].recv (.\L.0  (\A_d[0][0] ),
       .\L.1  (\A_d[1][0] ), .E (1'b1), .\L.e  (\A_e[0] ), .\R[0] 
       (\d[0] ));
  RECV_1of2_X2 \A_RECEIVE.recv.bits[10].recv (.\L.0  (\A_d[0][10] ),
       .\L.1  (\A_d[1][10] ), .E (1'b1), .\L.e  (\A_e[10] ), .\R[0] 
       (\d[10] ));
  RECV_1of2_X2 \A_RECEIVE.recv.bits[11].recv (.\L.0  (\A_d[0][11] ),
       .\L.1  (\A_d[1][11] ), .E (1'b1), .\L.e  (\A_e[11] ), .\R[0] 
       (\d[11] ));
  RECV_1of2_X2 \A_RECEIVE.recv.bits[12].recv (.\L.0  (\A_d[0][12] ),
       .\L.1  (\A_d[1][12] ), .E (1'b1), .\L.e  (\A_e[12] ), .\R[0] 
       (\d[12] ));
  RECV_1of2_X2 \A_RECEIVE.recv.bits[13].recv (.\L.0  (\A_d[0][13] ),
       .\L.1  (\A_d[1][13] ), .E (1'b1), .\L.e  (\A_e[13] ), .\R[0] 
       (\d[13] ));
  RECV_1of2_X2 \A_RECEIVE.recv.bits[14].recv (.\L.0  (\A_d[0][14] ),
       .\L.1  (\A_d[1][14] ), .E (1'b1), .\L.e  (\A_e[14] ), .\R[0] 
       (\d[14] ));
  RECV_1of2_X2 \A_RECEIVE.recv.bits[15].recv (.\L.0  (\A_d[0][15] ),
       .\L.1  (\A_d[1][15] ), .E (1'b1), .\L.e  (\A_e[15] ), .\R[0] 
       (\d[15] ));
  RECV_1of2_X2 \A_RECEIVE.recv.bits[1].recv (.\L.0  (\A_d[0][1] ),
       .\L.1  (\A_d[1][1] ), .E (1'b1), .\L.e  (\A_e[1] ), .\R[0] 
       (\d[1] ));
  RECV_1of2_X2 \A_RECEIVE.recv.bits[2].recv (.\L.0  (\A_d[0][2] ),
       .\L.1  (\A_d[1][2] ), .E (1'b1), .\L.e  (\A_e[2] ), .\R[0] 
       (\d[2] ));
  RECV_1of2_X2 \A_RECEIVE.recv.bits[3].recv (.\L.0  (\A_d[0][3] ),
       .\L.1  (\A_d[1][3] ), .E (1'b1), .\L.e  (\A_e[3] ), .\R[0] 
       (\d[3] ));
  RECV_1of2_X2 \A_RECEIVE.recv.bits[4].recv (.\L.0  (\A_d[0][4] ),
       .\L.1  (\A_d[1][4] ), .E (1'b1), .\L.e  (\A_e[4] ), .\R[0] 
       (\d[4] ));
  RECV_1of2_X2 \A_RECEIVE.recv.bits[5].recv (.\L.0  (\A_d[0][5] ),
       .\L.1  (\A_d[1][5] ), .E (1'b1), .\L.e  (\A_e[5] ), .\R[0] 
       (\d[5] ));
  RECV_1of2_X2 \A_RECEIVE.recv.bits[6].recv (.\L.0  (\A_d[0][6] ),
       .\L.1  (\A_d[1][6] ), .E (1'b1), .\L.e  (\A_e[6] ), .\R[0] 
       (\d[6] ));
  RECV_1of2_X2 \A_RECEIVE.recv.bits[7].recv (.\L.0  (\A_d[0][7] ),
       .\L.1  (\A_d[1][7] ), .E (1'b1), .\L.e  (\A_e[7] ), .\R[0] 
       (\d[7] ));
  RECV_1of2_X2 \A_RECEIVE.recv.bits[8].recv (.\L.0  (\A_d[0][8] ),
       .\L.1  (\A_d[1][8] ), .E (1'b1), .\L.e  (\A_e[8] ), .\R[0] 
       (\d[8] ));
  RECV_1of2_X2 \A_RECEIVE.recv.bits[9].recv (.\L.0  (\A_d[0][9] ),
       .\L.1  (\A_d[1][9] ), .E (1'b1), .\L.e  (\A_e[9] ), .\R[0] 
       (\d[9] ));
endmodule

